export type LocalizedName = [string, string];

export const CREATURE_TYPES: LocalizedName[] = [
  ['Aberration', '异怪'],
  ['Animal', '动物'],
  ['Construct', '构装生物'],
  ['Dragon', '龙类'],
  ['Fey', '妖精'],
  ['Humanoid', '类人生物'],
  ['Magical Beast', '魔法兽'],
  ['Monstrous Humanoid', '怪物类人生物'],
  ['Ooze', '泥怪'],
  ['Outsider', '异界生物'],
  ['Plant', '植物'],
  ['Undead', '不死生物'],
  ['Vermin', '虫类'],
];

export const CREATURE_SUBTYPES: LocalizedName[] = [
  ['Adlet', '狼妖'],
  ['Aeon', '御衡者'],
  ['Aether', '以太'],
  ['Agathion', '盖丁'],
  ['Air', '气系'],
  ['Android', '仿生人'],
  ['Angel', '天使'],
  ['Aquatic', '水生'],
  ['Archon', '亚空'],
  ['Astomoi', '阿斯托莫伊人'],
  ['Asura', '修罗'],
  ['Augmented (Aberration)', '增强(异怪)'],
  ['Augmented (Animal)', '增强(动物)'],
  ['Augmented (Construct)', '增强(构装生物)'],
  ['Augmented (Dragon)', '增强(龙类)'],
  ['Augmented (Fey)', '增强(妖精)'],
  ['Augmented (Humanoid)', '增强(类人生物)'],
  ['Augmented (Magical Beast)', '增强(魔法兽)'],
  ['Augmented (Monstrous Humanoid)', '增强(人形怪物)'],
  ['Augmented (Ooze)', '增强(泥怪)'],
  ['Augmented (Outsider)', '增强(异界生物)'],
  ['Augmented (Plant)', '增强(植物)'],
  ['Augmented (Undead)', '增强(不死生物)'],
  ['Augmented (Vermin)', '增强(虫类)'],
  ['Azata', '爱塔'],
  ['Behemoth', '比蒙巨兽'],
  ['Blight', '荒疫怪'],
  ['Catfolk', '猫族'],
  ['Changeling', '替换儿'],
  ['Chaotic', '混乱'],
  ['Clockwork', '发条'],
  ['Cold', '寒系'],
  ['Colossus', '巨神兵'],
  ['Daemon', '邪魔'],
  ['Dark Folk', '幽暗民'],
  ['Deep One', '深潜者'],
  ['Demodand', '魔孽'],
  ['Demon', '恶魔'],
  ['Derro', '迪洛矮人'],
  ['Devil', '魔鬼'],
  ['Dhampir', '吸血裔'],
  ['Div', '妖灵'],
  ['Dwarf', '矮人'],
  ['Earth', '土系'],
  ['Elemental', '元素'],
  ['Elf', '精灵'],
  ['Evil', '邪恶'],
  ['Extraplanar', '跨位面'],
  ['Fire', '火系'],
  ['Giant', '巨人'],
  ['Gnome', '侏儒'],
  ['Goblinoid', '地精类'],
  ['Good', '善良'],
  ['Gray', '小灰人'],
  ['Great Old One', '旧日支配者'],
  ['Grippli', '树蛙人'],
  ['Halfling', '半身人'],
  ['Herald', '使者'],
  ['Hive', '蜂巢群裔'],
  ['Human', '人类'],
  ['Incorporeal', '虚体'],
  ['Inevitable', '制裁者'],
  ['Kaiju', '怪兽'],
  ['Kami', '社神'],
  ['Kasatha', '卡萨塔'],
  ['Kitsune', '狐妖'],
  ['Kyton', '链魔'],
  ['Lawful', '守序'],
  ['Lashunta', '勒珊塔'],
  ['Leshy', '莱西'],
  ['Manasaputra', '圣仙'],
  ['Mortic', '莫提克'],
  ['Munavri', '白化人'],
  ['Mythic', '神话'],
  ['Native', '本地'],
  ['Nightshade', '夜影'],
  ['Oni', '恶鬼'],
  ['Orc', '兽人'],
  ['Phantom', '魅影'],
  ['Protean', '幻蛇'],
  ['Psychopomp', '死神使者'],
  ['Qlippoth', '古魔'],
  ['Rakshasa', '罗刹'],
  ['Ratfolk', '鼠人'],
  ['Reptilian', '爬虫'],
  ['Robot', '机体'],
  ['Sahkil', '恐亡魔'],
  ['Samsaran', '轮回者'],
  ['Sasquatch', '大脚'],
  ['Shapechanger', '变形'],
  ['Skinwalker', '兽态人'],
  ['Spawn of Rovagug', '罗瓦古格之卵'],
  ['Strix', '鸮形人'],
  ['Swarm', '集群'],
  ['Tengu', '天狗'],
  ['Triaxian', '特里亚克萨斯'],
  ['Troop', '部队'],
  ['Vanara', '灵猴族'],
  ['Vishkanya', '蝮血裔'],
  ['Water', '水系'],
  ['Wayang', '剪影人'],
  ['Wild Hunt', '狂猎'],
];
