export type LocalizedName = [string, string];

export const CREATURE_TYPES: LocalizedName[] = [
  ['Aberration', '异怪'],
  ['Animal', '动物'],
  ['Construct', '构装生物'],
  ['Dragon', '龙类'],
  ['Fey', '妖精'],
  ['Humanoid', '类人生物'],
  ['Magical Beast', '魔法兽'],
  ['Monstrous Humanoid', '怪物类人生物'],
  ['Ooze', '泥怪'],
  ['Outsider', '异界生物'],
  ['Plant', '植物'],
  ['Undead', '不死生物'],
  ['Vermin', '虫类'],
];

export const CREATURE_SUBTYPES: LocalizedName[] = [
  ['Adlet', '狼妖'],
  ['Aeon', '至高天顶/御衡者'],
  ['Aether', '以太'],
  ['Agathion', '盖丁天界生物'],
  ['Air', '气系'],
  ['Android', '人造人'],
  ['Angel', '天使'],
  ['Aquatic', '水生'],
  ['Archon', '亚空天界生物'],
  ['Astomoi', '无口族'],
  ['Asura', '修罗'],
  ['Augmented (Aberration)', '进化(异怪)'],
  ['Augmented (Animal)', '进化(动物)'],
  ['Augmented (Construct)', '进化(构装生物)'],
  ['Augmented (Dragon)', '进化(龙类)'],
  ['Augmented (Fey)', '进化(妖精)'],
  ['Augmented (Humanoid)', '进化(类人生物)'],
  ['Augmented (Magical Beast)', '进化(魔法兽)'],
  ['Augmented (Monstrous Humanoid)', '进化(怪物类人生物)'],
  ['Augmented (Ooze)', '进化(泥怪)'],
  ['Augmented (Outsider)', '进化(异界生物)'],
  ['Augmented (Plant)', '进化(植物)'],
  ['Augmented (Undead)', '进化(不死生物)'],
  ['Augmented (Vermin)', '进化(虫类)'],
  ['Azata', '爱塔天界生物'],
  ['Behemoth', '巨兽'],
  ['Blight', '荒疫生物'],
  ['Catfolk', '猫族'],
  ['Changeling', '换生灵'],
  ['Chaotic', '混乱'],
  ['Clockwork', '发条'],
  ['Cold', '寒系'],
  ['Colossus', '巨神兵'],
  ['Daemon', '邪魔'],
  ['Dark Folk', '黑暗民'],
  ['Deep One', '深潜者'],
  ['Demodand', '缚灵魔'],
  ['Demon', '恶魔'],
  ['Derro', '迪洛矮人'],
  ['Devil', '魔鬼'],
  ['Dhampir', '吸血裔'],
  ['Div', '狄甫'],
  ['Dwarf', '矮人'],
  ['Earth', '土系'],
  ['Elemental', '元素'],
  ['Elf', '精灵'],
  ['Evil', '邪恶'],
  ['Extraplanar', '跨位面'],
  ['Fire', '火系'],
  ['Giant', '巨人'],
  ['Gnome', '侏儒'],
  ['Goblinoid', '地精类'],
  ['Good', '善良'],
  ['Gray', '灰人'],
  ['Great Old One', '旧日支配者'],
  ['Grippli', '蛙人'],
  ['Halfling', '半身人'],
  ['Herald', '使者'],
  ['Hive', '蜂巢群裔'],
  ['Human', '人类'],
  ['Incorporeal', '虚体'],
  ['Inevitable', '密使'],
  ['Kaiju', '怪兽'],
  ['Kami', '神道精魂'],
  ['Kasatha', '卡萨斯人'],
  ['Kitsune', '狐妖'],
  ['Kyton', '链魔'],
  ['Lawful', '守序'],
  ['Lashunta', '勒珊塔'],
  ['Leshy', '莱西'],
  ['Manasaputra', '心生子'],
  ['Mortic', '莫提克'],
  ['Munavri', '白化妖'],
  ['Mythic', '神话'],
  ['Native', '本地'],
  ['Nightshade', '夜影'],
  ['Oni', '鬼'],
  ['Orc', '兽人'],
  ['Phantom', '幻灵'],
  ['Protean', '变幻魔'],
  ['Psychopomp', '死神使者'],
  ['Qlippoth', '古魔'],
  ['Rakshasa', '罗刹'],
  ['Ratfolk', '鼠人'],
  ['Reptilian', '爬虫类'],
  ['Robot', '机器人'],
  ['Sahkil', '恐惧魔'],
  ['Samsaran', '转生灵'],
  ['Sasquatch', '大脚怪'],
  ['Shapechanger', '变形生物'],
  ['Skinwalker', '兽态人'],
  ['Spawn of Rovagug', '罗瓦古格之卵'],
  ['Strix', '鸮形人'],
  ['Swarm', '集群'],
  ['Tengu', '天狗'],
  ['Triaxian', '特里亚克萨斯'],
  ['Troop', '军队'],
  ['Vanara', '灵猴族'],
  ['Vishkanya', '蝮血裔'],
  ['Water', '水系'],
  ['Wayang', '影皮人'],
  ['Wild Hunt', '荒野狂猎'],
];
