export const DEITIES_BY_PANTHEON: Record<string, string[]> = {
  "Core Deities": [
    "Erastil",
    "Iomedae",
    "Torag",
    "Sarenrae",
    "Shelyn",
    "Cayden Cailean",
    "Desna",
    "Abadar",
    "Irori",
    "Gozreh",
    "Green Faith",
    "Nethys",
    "Pharasma",
    "Calistria",
    "Gorum",
    "Asmodeus",
    "Zon-Kuthon",
    "Norgorber",
    "Urgathoa",
    "Lamashtu",
    "Rovagug"
  ],
  "Other Deities": [
    "Apsu",
    "Easivra",
    "Gruhastha",
    "Cihua Couatl",
    "Kazutal",
    "Kurgess",
    "Mazludeh",
    "Omrataji",
    "Milani",
    "Alseta",
    "Erecura",
    "Matravash",
    "Brigh",
    "Feronia",
    "Grandmother Spider",
    "Naderi",
    "Nivi Rhombodazzle",
    "Sivanah",
    "Ashukharma",
    "Besmara",
    "Groetus",
    "Hanspur",
    "Nocticula (Redeemed)",
    "Speakers of the Depths",
    "Achaekek",
    "Dhalavei",
    "Lissala",
    "Ah Pook",
    "Ahriman",
    "Alazhra",
    "Arazni",
    "Zyphus",
    "Camazotz",
    "Dahak",
    "Ghlaunder",
    "Gyronna",
    "Kitumu",
    "Ydersius"
  ],
  "Aeon": [
    "Monad"
  ],
  "Archdevils": [
    "Baalzebul",
    "Barbatos",
    "Belial",
    "Dispater",
    "Geryon",
    "Mammon",
    "Mephistopheles",
    "Moloch"
  ],
  "Asura Ranas": [
    "Andak",
    "Bohga",
    "Chugarra",
    "Chupurvagasti",
    "Gavidya",
    "Hydim",
    "Ioramvol",
    "Maeha",
    "Onamahli",
    "Rahu",
    "Rytara",
    "Taraksun",
    "Zurapadyn"
  ],
  "Azlanti Pantheon": [
    "Aesocar",
    "Myr",
    "Jaidi",
    "Shelyn (pre-Earthfall)",
    "Elion",
    "Amaznen",
    "Lissala (pre-Earthfall)",
    "Onos",
    "Acavna",
    "Sicva",
    "Scal",
    "Ulon"
  ],
  "Daemon Harbingers": [
    "Aesdurath",
    "Ajids",
    "Anogetz",
    "Arlachramas",
    "Braismois",
    "Cixyron",
    "Corosbel",
    "Diceid",
    "Ealdeez",
    "Folca",
    "Geon",
    "Hastrikhal",
    "Jacarkas",
    "Laivatiniel",
    "Llamolaek",
    "Mneoc",
    "Nalmungder",
    "Osolmyr",
    "Pavnuri",
    "Roqorolos",
    "Ruapceras",
    "Slandrais",
    "Stygidvod",
    "Tamede",
    "Tresmalvos",
    "Uaransaph",
    "Vorasha",
    "Xsistaid",
    "Zaigasnar",
    "Zelishkar"
  ],
  "Dead Deities": [
    "Aroden"
  ],
  "Deities of Ancient Osirion": [
    "Osiris",
    "Wadjet",
    "Bes",
    "Isis",
    "Khepri",
    "Neith",
    "Hathor",
    "Selket",
    "Anubis",
    "Horus",
    "Maat",
    "Ra",
    "Thoth",
    "Ptah",
    "Bastet",
    "Nephthys",
    "Sekhmet",
    "Sobek",
    "Set",
    "Apep"
  ],
  "Deities of Tian Xia": [
    "Shizuru",
    "Tsukiyo",
    "Qi Zhong",
    "Kofusachi",
    "Daikitsu",
    "Nalinivati",
    "Yamatsumi",
    "Hei Feng",
    "Sun Wukong",
    "General Susumu",
    "Yaezhing",
    "Fumeiyoshi",
    "Lao Shu Po",
    "Lady Nanbyo"
  ],
  "Demon Lords": [
    "Abraxas",
    "Aldinach",
    "Andirifkhu",
    "Angazhan",
    "Areshkagal",
    "Baphomet",
    "Cyth-V'sug",
    "Dagon",
    "Deskari",
    "Flauros",
    "Gogunta",
    "Haagenti",
    "Jezelda",
    "Jubilex",
    "Kabriri",
    "Kostchtchie",
    "Mazmezz",
    "Mestama",
    "Nocticula",
    "Nurgal",
    "Orcus",
    "Pazuzu",
    "Shax",
    "Shivaska",
    "Sifkesh",
    "Socothbenoth",
    "Urxehl",
    "Xoveron",
    "Yhidothrus",
    "Zevgavizeb",
    "Zura"
  ],
  "Dwarven Deities": [
    "Angradd",
    "Folgrit",
    "Grundinnar",
    "Bolka",
    "Trudd",
    "Dranngvit",
    "Kols",
    "Magrim",
    "Droskar"
  ],
  "Eldest": [
    "Imbrex",
    "Magdh",
    "Ng",
    "Shyka",
    "The Lost Prince",
    "Count Ranalc",
    "The Lantern King",
    "The Green Mother",
    "Ragadahn"
  ],
  "Elemental Lords": [
    "Ayrzul",
    "Hshurha",
    "Kelizandri",
    "Ymeri"
  ],
  "Elven Deities": [
    "Yuelral",
    "Findeladlara",
    "Ketephys"
  ],
  "Empyreal Lords": [
    "Andoletta",
    "Arqueros",
    "Damerrich",
    "Eldas",
    "Falayna",
    "Ghenshau",
    "Kelinahat",
    "Kroina",
    "Lymnieris",
    "Neshen",
    "Olheon",
    "Ragathiel",
    "Smiad",
    "Svarozic",
    "Tanagaar",
    "Vildeis",
    "Winlas",
    "Zohls",
    "Arshea",
    "Benorus",
    "Bharnarol",
    "Dalenydra",
    "Eritrice",
    "Halcamora",
    "Irez",
    "Jaidz",
    "Korada",
    "Lorris",
    "Lythertida",
    "Ondisso",
    "Rowdrosh",
    "Seramaydiel",
    "Shei",
    "Soralyon",
    "Uskyeria",
    "Ylimancha",
    "Ashava",
    "Black Butterfly",
    "Cernunnos",
    "Chadali",
    "Chucaro",
    "Hembad",
    "Immonhiel",
    "Jalaijatali",
    "Keltheald",
    "Lalaci",
    "Marishi",
    "Picoperi",
    "Pulura",
    "Reymenda",
    "Sinashakti",
    "Thisamet",
    "Tolc",
    "Valani"
  ],
  "Giant Deities": [
    "Aegirran",
    "Bergelmir",
    "Skode",
    "Skrymir",
    "Fandarra",
    "Tjasse",
    "Minderhal",
    "Zursvaater",
    "Haggakal",
    "Thremyr",
    "Urazra"
  ],
  "Goblin Hero-Gods": [
    "Hadregash",
    "Venkelvore",
    "Zarongel",
    "Zogmugot"
  ],
  "Great Old One": [
    "Tawil at'Umr"
  ],
  "Great Old Ones": [
    "Bokrug",
    "Mhar",
    "Yig",
    "Atlach-Nacha",
    "Ghatanothoa",
    "Xhamen-Dor",
    "Chaugnar Faugn",
    "Cthulhu",
    "Hastur",
    "Ithaqua",
    "Mordiggian",
    "Orgesh",
    "Rhan-Tegoth",
    "Tsathoggua"
  ],
  "Halfling Deities": [
    "Chaldira",
    "Thamir Gixx"
  ],
  "Horsemen": [
    "Apollyon",
    "Charon",
    "Szuriel",
    "Trelmarixian"
  ],
  "Iblydan Hero-Gods": [
    "Chinostes (Good Aspect)",
    "Kelksiomides",
    "Upion and Warrik",
    "Psomeira",
    "Aerekostes",
    "Drokalion",
    "Iapholi",
    "Chinostes (Evil Aspect)",
    "Ongalte",
    "Pharimia"
  ],
  "Infernal Dukes": [
    "Alocer",
    "Bifrons",
    "Crocell",
    "Deumus",
    "Eaqueo",
    "Eligos",
    "Furcas",
    "Gaap",
    "Haborym",
    "Iaozrael",
    "Jiraviddain",
    "Kalma",
    "Lorcan",
    "Lorthact",
    "Losarkur",
    "Malthus",
    "Nergal",
    "Ose",
    "Pirias",
    "Quindiovatos",
    "Rasvocel",
    "Ruzel",
    "Sabnach",
    "Titivilus",
    "Uruskreil",
    "Vapula",
    "Vois",
    "Wylgart",
    "Xhasnaphar",
    "Yan-gant-y-tan",
    "Zaebos",
    "Zepar"
  ],
  "Kyton Demagogues": [
    "Aroggus",
    "Barravoclair",
    "Fharaas",
    "Inkariax",
    "Kaikyton",
    "Morrobahn",
    "Raetorgash",
    "Sugroz",
    "Vevelor"
  ],
  "Malebranche": [
    "Alichino",
    "Barbariccia",
    "Cagnazzo",
    "Calcabrina",
    "Circiatto",
    "Draghignazzo",
    "Farfarello",
    "Graffiacane",
    "Libicocco",
    "Malacoda",
    "Rubicante",
    "Scarmiglione"
  ],
  "Nascent Demon Lords": [
    "Daclau-Sar",
    "Izyagna",
    "Kro'akoth",
    "Menxyr",
    "Murnath",
    "Nightripper",
    "Ovonovo",
    "Shamira",
    "Sithhud",
    "Treerazer"
  ],
  "Oni Daimyo": [
    "Akuma",
    "Inma",
    "Uzumae",
    "Chimon",
    "Muronna",
    "Nataka",
    "Yabu",
    "Guyuku",
    "Onmyuza",
    "Ushitora"
  ],
  "Orc Deities": [
    "Dretha",
    "Lanishra",
    "Nulgreth",
    "Rull",
    "Sezelrian",
    "Varg",
    "Verex",
    "Zagresh"
  ],
  "Outer Gods": [
    "Abhoth",
    "Azathoth",
    "Yog-Sothoth",
    "Nhimbaloth",
    "Nyarlathotep (Black Pharaoh)",
    "Nyarlathotep (Faceless Sphinx)",
    "Nyarlathotep (Haunter of the Dark)",
    "Shub-Niggurath"
  ],
  "Primal Inevitable": [
    "Jerishall",
    "Kerkamoth",
    "Otolmens",
    "Valmallos"
  ],
  "Protean Lord": [
    "Il'surrish",
    "Narriseminek",
    "Ssila'meshnik",
    "Ydajisk"
  ],
  "Psychopomp Usher": [
    "Atropos",
    "Barzahk",
    "Ceyannan",
    "Dammar",
    "Imot",
    "Mother Vulture",
    "Mrtyu",
    "Narakaas",
    "Phlegyas",
    "Saloc",
    "Teshallas",
    "The Pale Horse",
    "Vale",
    "Vavaalrav",
    "Vonymos"
  ],
  "Qlippoth Lords": [
    "Chavazvug",
    "Isph-Aun-Vuln",
    "Oaur-Ooung",
    "Shiggarreb",
    "Thuskchoon",
    "Yamasoth"
  ],
  "Queens of the Night": [
    "Ardad Lili",
    "Doloras",
    "Eiseth",
    "Mahathallah"
  ],
  "Rakshasa Immortals": [
    "Aksha",
    "Bundha",
    "Caera",
    "Dradjit",
    "Hudima",
    "Jyotah",
    "Kunkarna",
    "Mursha",
    "Otikaya",
    "Prihasta",
    "Ravana",
    "Surpa",
    "Vibhishah",
    "Zabha"
  ],
  "Sahkil Tormentors": [
    "Ananshea",
    "Chamiaholom",
    "Charg",
    "Dachzerul",
    "Hataam",
    "Iggeret",
    "Nameless",
    "Ozranvial",
    "Shawnari",
    "Velgaas",
    "Vermilion Mother",
    "Xiquiripat",
    "Zipacna"
  ]
};