import { CharacterData } from './types';

export const DEFAULT_DATA: CharacterData = {
  basic: {
    name: '新人物',
    classes: '',
    alignment: '',
    size: '',
    gender: '',
    race: '',
    age: '',
    height: '',
    weight: '',
    speed: '',
    senses: '',
    initiative: '',
    perception: '',
    languages: '',
    deity: '',
    avatars: [] as { url: string; note: string }[],
  },
  story: '',
  attributes: [
    { name: '力量', final: '10', modifier: '+0', source: '10', status: '' },
    { name: '敏捷', final: '10', modifier: '+0', source: '10', status: '' },
    { name: '体质', final: '10', modifier: '+0', source: '10', status: '' },
    { name: '智力', final: '10', modifier: '+0', source: '10', status: '' },
    { name: '感知', final: '10', modifier: '+0', source: '10', status: '' },
    { name: '魅力', final: '10', modifier: '+0', source: '10', status: '' }
  ],
  babCmbCmd: '',
  meleeAttacksOverview: '',
  meleeAttacks: [],
  rangedAttacksOverview: '',
  rangedAttacks: [],
  specialAttacks: '',
  defenses: { ac: '', hp: '', saves: '' },
  racialTraits: [],
  backgroundTraits: [],
  favoredClass: '',
  favoredClassBonus: '',
  classFeatures: [],
  feats: [],
  magicBlocks: [] as any[],
  skills: [],
  skillsTotal: { name: '总计', total: '0', source: '', special: '' },
  equipmentBags: [],
  encumbranceMultiplier: '1',
  equipmentNotes: '',
  additionalData: [] as any[]
};
