import { CharacterData } from './types';

export const DEFAULT_DATA: CharacterData = {
  basic: {
    name: '新人物',
    classes: '',
    alignment: '',
    size: '',
    gender: '',
    race: '',
    age: '',
    height: '',
    weight: '',
    speed: '',
    senses: '',
    initiative: '',
    perception: '',
    languages: '',
    deity: '',
    avatars: [] as { url: string; note: string }[],
  },
  story: '',
  attributes: [
    { final: '10', modifier: '0', source: '', status: '' },
    { final: '10', modifier: '0', source: '', status: '' },
    { final: '10', modifier: '0', source: '', status: '' },
    { final: '10', modifier: '0', source: '', status: '' },
    { final: '10', modifier: '0', source: '', status: '' },
    { final: '10', modifier: '0', source: '', status: '' }
  ],
  babTable: [{ bab: '', cmb: '', cmd: '' }],
  combatManeuverNotes: '',
  meleeAttacks: [],
  rangedAttacks: [],
  specialAttacks: '',
  defenses: {
    hp: '',
    hd: '',
    acTable: [{ ac: '', flatFooted: '', touch: '' }],
    acNotes: '',
    savesTable: [{ fort: '', ref: '', will: '' }],
    savesNotes: ''
  },
  racialTraits: [],
  backgroundTraits: [],
  favoredClass: '',
  favoredClassBonus: '',
  classFeatures: [],
  feats: [],
  magicBlocks: [] as any[],
  skills: [],
  skillsTotal: { total: '0', source: '', special: '' },
  equipmentBags: [],
  encumbranceMultiplier: '1',
  equipmentNotes: '',
  additionalData: [] as any[]
};
